services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: nutritiondb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d nutritiondb"]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n:
   image: n8nio/n8n
   ports:
     - "5678:5678"
   environment:
    - N8N_BASIC_AUTH_ACTIVE=false  # Ou true avec des identifiants simples
    # - N8N_BASIC_AUTH_USER=admin
    # - N8N_BASIC_AUTH_PASSWORD=admin123
   volumes:
    - n8n_data:/home/node/.n8n

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://appuser:apppass@postgres:5432/nutritiondb
      - N8N_URL=http://n8n:5678
      - N8N_USERNAME=zeinebbennaceur1@gmail.com
      - N8N_PASSWORD=Z.bennaceur23203@pi.tn
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api/app:/app

volumes:
  postgres_data:
  n8n_data: